"""Core object contracts for StelligenOS.

``core`` is the legacy ``core_objects@1.1`` registry (eight object types),
retained during the runtime migration. ``decision_model`` is the Blueprint v1.3
decision-layer object set introduced by Runtime Migration PR A;
``legacy_adapters`` maps the former to the latter. ``gate_model`` (PR B) adds the
two-rule-layer Gate system contracts (``Gate`` / ``GateSet`` / ``EvidenceLadder``
/ ``Decision``); ``legacy_gate_map`` is the frozen-45-gate migration reference.
``evidence_reference_model`` (PR C) adds the derived ``MatrixView`` and the
reusable-evidence reference layer (evidence / source / per-gate index) with the
provenance-walk integrity checks.
"""

from .core import CORE_OBJECT_TYPES, CoreObject
from .decision_model import (
    CANDIDATE_LEVELS,
    CANONICAL_REVIEW_STATUS,
    DECISION_OBJECTS,
    DIRECTION_VALUES,
    EVIDENCE_REGIME_VALUES,
    EVIDENCE_ROLE_VALUES,
    GRADED_STRENGTHS,
    STRENGTH_VALUES,
    Candidate,
    CandidateGateAssessment,
    Context,
    EvidencePackage,
    EvidenceRef,
    Instantiation,
    field_names,
)
from .legacy_adapters import (
    LEGACY_CROSSWALK,
    MISSING_CANDIDATE_TYPES,
    ONE_TO_ONE_LEGACY_TYPES,
    LegacyCrosswalkEntry,
    adapt_core_object_to_candidate,
)
from .gate_model import (
    CANONICAL_GATESET_IDS,
    DECISION_VALUES,
    DOMINANT_EVIDENCE_REGIMES,
    LADDER_GRADES,
    Decision,
    EvidenceLadder,
    Gate,
    GateSet,
    GateSetMember,
    LadderRung,
    TriggeredBy,
)
from .legacy_gate_map import (
    LEGACY_GATE_SYSTEM,
    LEGACY_GATECHAIN_CROSSWALK,
    LegacyGatechainCrosswalk,
    LegacyGateSystem,
)
from .evidence_reference_model import (
    EVIDENCE_INDEX_STATUS_VALUES,
    MATRIX_CELL_STATES,
    EvidenceIndexEntry,
    EvidenceLibraryIndex,
    GateEvidenceIndex,
    GateEvidenceIndexEntry,
    MatrixRow,
    MatrixView,
    SourceIndex,
    SourceIndexEntry,
    check_assessment_evidence_refs_against_packages,
    check_evidence_index_against_packages,
    check_evidence_library_against_sources,
    check_gate_index_against_assessments,
    check_gate_index_against_library,
    check_matrix_against_assessments,
    check_matrix_cells_are_backed,
    check_packages_against_sources,
    check_supersession_consistency,
    serialized_matrix_cell,
)

__all__ = [
    "CORE_OBJECT_TYPES",
    "CoreObject",
    "CANDIDATE_LEVELS",
    "CANONICAL_REVIEW_STATUS",
    "DECISION_OBJECTS",
    "DIRECTION_VALUES",
    "EVIDENCE_REGIME_VALUES",
    "EVIDENCE_ROLE_VALUES",
    "GRADED_STRENGTHS",
    "STRENGTH_VALUES",
    "Candidate",
    "CandidateGateAssessment",
    "Context",
    "EvidencePackage",
    "EvidenceRef",
    "Instantiation",
    "field_names",
    "LEGACY_CROSSWALK",
    "MISSING_CANDIDATE_TYPES",
    "ONE_TO_ONE_LEGACY_TYPES",
    "LegacyCrosswalkEntry",
    "adapt_core_object_to_candidate",
    "CANONICAL_GATESET_IDS",
    "DECISION_VALUES",
    "DOMINANT_EVIDENCE_REGIMES",
    "LADDER_GRADES",
    "Decision",
    "EvidenceLadder",
    "Gate",
    "GateSet",
    "GateSetMember",
    "LadderRung",
    "TriggeredBy",
    "LEGACY_GATE_SYSTEM",
    "LEGACY_GATECHAIN_CROSSWALK",
    "LegacyGatechainCrosswalk",
    "LegacyGateSystem",
    "EVIDENCE_INDEX_STATUS_VALUES",
    "MATRIX_CELL_STATES",
    "EvidenceIndexEntry",
    "EvidenceLibraryIndex",
    "GateEvidenceIndex",
    "GateEvidenceIndexEntry",
    "MatrixRow",
    "MatrixView",
    "SourceIndex",
    "SourceIndexEntry",
    "check_assessment_evidence_refs_against_packages",
    "check_evidence_index_against_packages",
    "check_evidence_library_against_sources",
    "check_gate_index_against_assessments",
    "check_gate_index_against_library",
    "check_matrix_against_assessments",
    "check_matrix_cells_are_backed",
    "check_packages_against_sources",
    "check_supersession_consistency",
    "serialized_matrix_cell",
]
